# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

sudo: false
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - source tests/travis_install.sh
  - pip install -r test-requirements.txt
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
