name: pyrate
dependencies:
- alabaster
- babel
- docutils
- jinja2
- markupsafe
- numpy
- openssl
- pandas
- pip
- psycopg2
- pygments
- python=3.3.5=3
- python-dateutil
- pytz
- readline
- scipy
- setuptools
- six
- snowballstemmer
- sphinx
- sphinx_rtd_theme
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - commonmark
  - geographiclib
  - geopy
  - recommonmark
  - sphinx-rtd-theme
